// src/app/auth/signup/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { useToast } from '@/hooks/use-toast'
import { Eye, EyeOff } from 'lucide-react'

export default function SignUpPage() {
  const [formData, setFormData] = useState({
    name: '',
    username: '',
    email: '',
    password: ''
  })
  const [showPassword, setShowPassword] = useState(false)
  const [loading, setLoading] = useState(false)
  const router = useRouter()
  const { toast } = useToast()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)

    try {
      const response = await fetch('/api/server/auth/signup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
        credentials: 'include'
      })

      const data = await response.json()

      if (response.ok) {
        toast({
          title: 'Success',
          description: 'Account created successfully!',
        })
        router.push('/notes')
      } else {
        toast({
          title: 'Error',
          description: data.error || 'Sign up failed',
          variant: 'destructive'
        })
      }
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Network error. Please try again.',
        variant: 'destructive'
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Create a new account</CardTitle>
          <CardDescription>
            Sign up to start creating voice notes
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label htmlFor="name">Full Name</Label>
              <Input
                id="name"
                type="text"
                value={formData.name}
                onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                placeholder="Enter your full name"
                required
              />
            </div>

            <div>
              <Label htmlFor="username">Username</Label>
              <Input
                id="username"
                type="text"
                value={formData.username}
                onChange={(e) => setFormData(prev => ({ ...prev, username: e.target.value }))}
                placeholder="Choose a username"
                required
              />
            </div>

            <div>
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                value={formData.email}
                onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                placeholder="Enter your email"
                required
              />
            </div>

            <div>
              <Label htmlFor="password">Password</Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  value={formData.password}
                  onChange={(e) => setFormData(prev => ({ ...prev, password: e.target.value }))}
                  placeholder="Create a password"
                  required
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                  onClick={() => setShowPassword(!showPassword)}
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </Button>
              </div>
            </div>

            <Button type="submit" className="w-full" disabled={loading}>
              {loading ? 'Creating account...' : 'Create account'}
            </Button>
          </form>

          <div className="mt-6 text-center text-sm">
            Already have an account?{' '}
            <Link href="/auth/signin" className="text-primary hover:underline">
              Sign in here
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// app/pages/sign-up.vue
<template>
  <UCard class="max-w-sm w-full">
    <h2 class="text-2xl font-medium text-center">Create a new account</h2>

    <UForm ref="form" :schema="signUpSchema" :state="state" class="space-y-4 my-6" @submit="onSignUp">
      <UFormField name="name" label="Name" required>
        <UInput v-model.trim="state.name" placeholder="Enter your name" icon="i-lucide-user" class="w-full" />
      </UFormField>

      <UFormField name="username" label="Username" required>
        <UInput v-model.trim="state.username" placeholder="Enter you username" icon="i-lucide-at-sign" class="w-full" />
      </UFormField>
      <UFormField name="email" label="Email" required>
        <UInput v-model="state.email" placeholder="you@example.com" type="email" />
      </UFormField>
      <UFormField name="password" label="Password" required>
        <UInput v-model.trim="state.password" class="w-full" icon="i-lucide-key-round" placeholder="Enter your password"
          :type="showPassword ? 'text' : 'password'" :ui="{ trailing: 'pe-1' }">
          <template #trailing>
            <UButton aria-controls="password" color="neutral" variant="link"
              :aria-label="showPassword ? 'Hide password' : 'Show password'" :aria-pressed="showPassword"
              :icon="showPassword ? `i-lucide-eye-off` : `i-lucide-eye`" @click="showPassword = !showPassword" />
          </template>
        </UInput>
      </UFormField>

      <UButton block class="mt-2" trailing-icon="i-lucide-arrow-right" type="submit" :disabled="loading"
        :loading="loading" :ui="{ trailingIcon: 'ms-0' }">
        Submit
      </UButton>
    </UForm>

    <div class="text-sm font-medium text-gray-500 dark:text-gray-300 text-center">
      Already have an account?
      <ULink class="text-[var(--ui-primary)] hover:text-[var(--ui-primary)]/75" to="/sign-in">
        Sign in here
      </ULink>
    </div>
  </UCard>
</template>

<script setup lang="ts">
import { FetchError } from "ofetch";
import { signUpSchema } from "#shared/schemas/auth.schema";
import type { Form, FormSubmitEvent } from "#ui/types";

const showPassword = ref(false);
const loading = ref(false);
const form = useTemplateRef<Form<SignUpSchemaType>>("form");
const state = reactive<Partial<SignUpSchemaType>>({
  name: undefined,
  username: undefined,
  email: undefined,
 
  password: undefined,
});

const toast = useToast();
const { fetch: refreshSession } = useUserSession();
const onSignUp = async (event: FormSubmitEvent<SignUpSchemaType>) => {
  loading.value = true;
  form.value?.clear();

  try {
    await $fetch("/api/auth/signup", {
      method: "POST",
      body: {
        name: event.data.name,
        username: event.data.username,
        email:    event.data.email,    // ← add this!

        password: event.data.password,
      },
    });

    toast.add({
      title: "Success",
      description: "Sign up successful.",
      color: "success",
    });

    await refreshSession();
  } catch (error) {
    let errorMsg = "Failed to sign up. Please try again later.";

    if (error instanceof FetchError) {
      if (error.data?.statusCode === 400 && error.data.data?.issues) {
        form.value?.setErrors(
          error.data.data.issues.map(
            (err: { message: string; path: string[] }) => ({
              message: err.message,
              name: err.path[0],
            }),
          ),
        );
      }

      if (error.data?.statusMessage) {
        errorMsg = error.data.statusMessage;
      }
    }

    toast.add({
      title: "Error",
      description: errorMsg,
      color: "error",
    });
  } finally {
    loading.value = false;
  }
};

definePageMeta({
  layout: "auth",
});
</script>
