// app/components/NoteEditorModal.vue
<template>
  <UModal
    fullscreen
    :close="{ disabled: isSaving || recorderBusy }"
    :prevent-close="isSaving || recorderBusy"
    :title="isEditing ? 'Edit Note' : 'Create Note'"
    :ui="{
      body: 'flex-1 w-full max-w-7xl mx-auto flex flex-col md:flex-row gap-4 sm:gap-6 overflow-hidden',
    }"
  >
    <template #body>
      <div class="md:flex gap-6">
        <!-- Left: transcript + recorder -->
        <div class="flex-1 space-y-4">
          <TranscriptDisplay :transcript="noteText" />

          <NoteRecorder
            ref="recorder"
            class="md:h-full md:flex md:flex-col md:w-200 shrink-0 order-first md:order-none"
            :audio-urls="note?.audioUrls"
            @transcription="handleTranscription"
          />
        </div>

        <!-- Right: auto-filled form -->
        <div class="md:w-1/3">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6 p-6 bg-gray-900 rounded-lg">
            <UFormField name="callerName" label="Caller Name" required>
              <UInput v-model="callerName" placeholder="John Doe" />
            </UFormField>

            <UFormField name="callerEmail" label="Caller Email" required>
              <UInput
                v-model="callerEmail"
                placeholder="john@example.com"
                type="email"
              />
            </UFormField>

            <UFormField name="callerLocation" label="Caller Location" required>
              <UInput v-model="callerLocation" placeholder="New York, NY" />
            </UFormField>

            <UFormField name="callerAddress" label="Caller Address" required>
              <UInput
                v-model="callerAddress"
                placeholder="123 Main St, Apt 4B"
              />
            </UFormField>

            <UFormField name="callReason" label="Reason for Call" required>
              <UTextarea
                v-model="callReason"
                placeholder="Project kick-off"
              />
            </UFormField>
          </div>
        </div>
      </div>
    </template>

    <template #footer>
      <UButton
        icon="i-lucide-undo-2"
        color="neutral"
        variant="outline"
        :disabled="isSaving"
        @click="resetNote"
      >
        Reset
      </UButton>

      <UButton
        icon="i-lucide-cloud-upload"
        :disabled="!noteText.trim() || recorderBusy || isSaving"
        :loading="isSaving"
        @click="saveNote"
      >
        {{ isEditing ? "Save Changes" : "Save Note" }}
      </UButton>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { NoteRecorder, TranscriptDisplay } from "#components";
import type { Note } from "./../../shared/schemas/note.schema";

const props = defineProps<{
  isEditing?: boolean;
  note?: Note;
  onEdit?: () => void;
}>();

// Form fields — initialize from props.note when editing
const callerName     = ref(props.note?.callerName   ?? "");
const callerEmail    = ref(props.note?.callerEmail  ?? "");
const callerLocation = ref(props.note?.callerLocation?? "");
const callerAddress  = ref(props.note?.callerAddress ?? "");
const callReason     = ref(props.note?.callReason    ?? "");

// Transcription text
const noteText = ref(props.note?.text ?? "");

// Grab the recorder component
type RecorderType = InstanceType<typeof NoteRecorder>;
const recorder = useTemplateRef<RecorderType>("recorder")!;

// A safe boolean for template binds
const recorderBusy = computed(() => recorder.value?.isBusy ?? false);

// Reset everything
const resetNote = () => {
 // reset text and form fields back to the original note values
 noteText.value     = props.note?.text           ?? "";
 callerName.value   = props.note?.callerName     ?? "";
 callerEmail.value  = props.note?.callerEmail    ?? "";
 callerLocation.value = props.note?.callerLocation?? "";
 callerAddress.value  = props.note?.callerAddress ?? "";
 callReason.value     = props.note?.callReason    ?? "";
  recorder.value?.resetRecordings();
};

/**  
 * Extract simple “my name is X” etc.  
 * We default each capture to empty string so TS can’t complain.  
 */
function extractFields(text: string) {
  for (const line of text.split(/\r?\n/)) {
    // Name
    const nameMatch = line.match(/(?:Hi|Hello|Good (?:Morning|Afternoon|Evening))\s+([A-Za-z]+)/i);
    if (nameMatch) {
      const capture = nameMatch[1] || "";
      callerName.value = capture.trim();
    }

    // Email
    const emailMatch = line.match(/(?:my email is|confirm (?:my )?email(?: address)?|email)[:\s]*([^\s]+)/i);
    if (emailMatch) {
      const capture = emailMatch[1] || "";
      callerEmail.value = capture.trim();
    }

    // Location
    const locMatch = line.match(/(?:my location is|I'm in|I am in|I live in)\s+(.+)/i)

    if (locMatch) {
      const capture = locMatch[1] || "";
      callerLocation.value = capture.trim();
    }

    // Address
    const addrMatch = line.match(/my address is\s+(.+)/i);
    if (addrMatch) {
      const capture = addrMatch[1] || "";
      callerAddress.value = capture.trim();
    }

    // Reason
    const reasonMatch = line.match(/(?:reason for call(?: is)?|I need help with)[:\s]*([\s\S]+)/i)

    if (reasonMatch) {
      const capture = reasonMatch[1] || "";
      callReason.value = capture.trim();
    }
  }
}

// Called on each transcription chunk
const handleTranscription = (text: string) => {
  noteText.value += noteText.value ? `\n\n${text}` : text;
  extractFields(text);
};

// Save logic
const isSaving = ref(false);
const saveNote = async () => {
  const text = noteText.value.trim();
  if (!text) return;

  isSaving.value = true;
  const audioUrls = await recorder.value?.uploadRecordings() ?? [];

  try {
    if (props.note) {
      // PATCH existing
      await $fetch(`/api/notes/${props.note.id}`, {
        method: "PATCH",
        body: {
          text,
          audioUrls,
          callerName: callerName.value,
          callerEmail: callerEmail.value,
          callerLocation: callerLocation.value,
          callerAddress: callerAddress.value,
          callReason: callReason.value,
        },
      });
    } else {
      // POST new
      await $fetch("/api/notes", {
        method: "POST",
        body: {
          text,
          audioUrls,
          callerName: callerName.value,
          callerEmail: callerEmail.value,
          callerLocation: callerLocation.value,
          callerAddress: callerAddress.value,
          callReason: callReason.value,
        },
      });
    }

    useToast().add({
      title: props.note ? "Note Updated" : "Note Saved",
      description: "Your note was saved successfully and Email has been send",
      color: "success",
    });
    recorder.value?.resetRecordings();
    if (props.onEdit) props.onEdit();
  } catch (err) {
    console.error("Error saving note:", err);
    useToast().add({
      title: "Save Failed",
      description: "Failed to save the note.",
      color: "error",
    });
  } finally {
    isSaving.value = false;
  }
};
</script>

// src/components/notes/note-editor-modal.tsx
'use client'

import { useState, useRef } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { useToast } from '@/hooks/use-toast'
import { NoteRecorder } from './note-recorder'
import { TranscriptDisplay } from './transcript-display'
import { Save, RotateCcw } from 'lucide-react'

interface Note {
  id: string
  text: string
  audioUrls?: string[]
  callerName: string
  callerEmail: string
  callerLocation: string
  callerAddress: string
  callReason: string
  createdAt: string
  updatedAt: string
}

interface NoteEditorModalProps {
  note?: Note | null
  onClose: () => void
  onSave: () => void
}

export function NoteEditorModal({ note, onClose, onSave }: NoteEditorModalProps) {
  const [formData, setFormData] = useState({
    callerName: note?.callerName || '',
    callerEmail: note?.callerEmail || '',
    callerLocation: note?.callerLocation || '',
    callerAddress: note?.callerAddress || '',
    callReason: note?.callReason || '',
  })
  const [noteText, setNoteText] = useState(note?.text || '')
  const [isSaving, setIsSaving] = useState(false)
  const recorderRef = useRef<any>(null)
  const { toast } = useToast()

  const extractFields = (text: string) => {
    const lines = text.split(/\r?\n/)
    
    for (const line of lines) {
      // Name
      const nameMatch = line.match(/(?:Hi|Hello|Good (?:Morning|Afternoon|Evening))\s+([A-Za-z]+)/i)
      if (nameMatch && nameMatch[1]) {
        setFormData(prev => ({ ...prev, callerName: nameMatch[1].trim() }))
      }

      // Email
      const emailMatch = line.match(/(?:my email is|confirm (?:my )?email(?: address)?|email)[:\s]*([^\s]+)/i)
      if (emailMatch && emailMatch[1]) {
        setFormData(prev => ({ ...prev, callerEmail: emailMatch[1].trim() }))
      }

      // Location
      const locMatch = line.match(/(?:my location is|I'm in|I am in|I live in)\s+(.+)/i)
      if (locMatch && locMatch[1]) {
        setFormData(prev => ({ ...prev, callerLocation: locMatch[1].trim() }))
      }

      // Address
      const addrMatch = line.match(/my address is\s+(.+)/i)
      if (addrMatch && addrMatch[1]) {
        setFormData(prev => ({ ...prev, callerAddress: addrMatch[1].trim() }))
      }

      // Reason
      const reasonMatch = line.match(/(?:reason for call(?: is)?|I need help with)[:\s]*([\s\S]+)/i)
      if (reasonMatch && reasonMatch[1]) {
        setFormData(prev => ({ ...prev, callReason: reasonMatch[1].trim() }))
      }
    }
  }

  const handleTranscription = (text: string) => {
    setNoteText(prev => prev ? `${prev}\n\n${text}` : text)
    extractFields(text)
  }

  const resetNote = () => {
    setNoteText(note?.text || '')
    setFormData({
      callerName: note?.callerName || '',
      callerEmail: note?.callerEmail || '',
      callerLocation: note?.callerLocation || '',
      callerAddress: note?.callerAddress || '',
      callReason: note?.callReason || '',
    })
    recorderRef.current?.resetRecordings()
  }

  const handleSave = async () => {
    if (!noteText.trim()) return

    setIsSaving(true)
    
    try {
      const audioUrls = await recorderRef.current?.uploadRecordings() || []
      
      const payload = {
        text: noteText,
        audioUrls,
        ...formData
      }

      const url = note ? `/api/server/notes/${note.id}` : '/api/server/notes'
      const method = note ? 'PATCH' : 'POST'

      const response = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
        credentials: 'include'
      })

      if (response.ok) {
        toast({
          title: note ? 'Note Updated' : 'Note Saved',
          description: 'Your note was saved successfully and email has been sent',
        })
        recorderRef.current?.resetRecordings()
        onSave()
        onClose()
      } else {
        throw new Error('Failed to save note')
      }
    } catch (error) {
      toast({
        title: 'Save Failed',
        description: 'Failed to save the note.',
        variant: 'destructive'
      })
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-6xl max-h-[90vh] overflow-hidden">
        <DialogHeader>
          <DialogTitle>{note ? 'Edit Note' : 'Create Note'}</DialogTitle>
        </DialogHeader>

        <div className="flex gap-6 flex-1 overflow-hidden">
          {/* Left: Transcript + Recorder */}
          <div className="flex-1 space-y-4">
            <TranscriptDisplay transcript={noteText} />
            <NoteRecorder
              ref={recorderRef}
              audioUrls={note?.audioUrls}
              onTranscription={handleTranscription}
            />
          </div>

          {/* Right: Form */}
          <div className="w-1/3 space-y-4">
            <div className="grid grid-cols-1 gap-4 p-4 bg-muted rounded-lg">
              <div>
                <Label htmlFor="callerName">Caller Name *</Label>
                <Input
                  id="callerName"
                  value={formData.callerName}
                  onChange={(e) => setFormData(prev => ({ ...prev, callerName: e.target.value }))}
                  placeholder="John Doe"
                />
              </div>

              <div>
                <Label htmlFor="callerEmail">Caller Email *</Label>
                <Input
                  id="callerEmail"
                  type="email"
                  value={formData.callerEmail}
                  onChange={(e) => setFormData(prev => ({ ...prev, callerEmail: e.target.value }))}
                  placeholder="john@example.com"
                />
              </div>

              <div>
                <Label htmlFor="callerLocation">Caller Location *</Label>
                <Input
                  id="callerLocation"
                  value={formData.callerLocation}
                  onChange={(e) => setFormData(prev => ({ ...prev, callerLocation: e.target.value }))}
                  placeholder="New York, NY"
                />
              </div>

              <div>
                <Label htmlFor="callerAddress">Caller Address *</Label>
                <Input
                  id="callerAddress"
                  value={formData.callerAddress}
                  onChange={(e) => setFormData(prev => ({ ...prev, callerAddress: e.target.value }))}
                  placeholder="123 Main St, Apt 4B"
                />
              </div>

              <div>
                <Label htmlFor="callReason">Reason for Call *</Label>
                <Textarea
                  id="callReason"
                  value={formData.callReason}
                  onChange={(e) => setFormData(prev => ({ ...prev, callReason: e.target.value }))}
                  placeholder="Project kick-off"
                />
              </div>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={resetNote} disabled={isSaving}>
            <RotateCcw className="w-4 h-4 mr-2" />
            Reset
          </Button>
          <Button 
            onClick={handleSave} 
            disabled={!noteText.trim() || isSaving}
            loading={isSaving}
          >
            <Save className="w-4 h-4 mr-2" />
            {note ? 'Save Changes' : 'Save Note'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
