// app/components/TranscriptDisplay.vue
<template>
  <div class="space-y-1 p-4 bg-gray-800 rounded-lg h-64 overflow-auto">
    <div
      v-for="(line, i) in lines"
      :key="i"
      class="flex items-start gap-2"
    >
      <UIcon name="i-lucide-mic" class="text-green-400" />
      <p class="text-sm text-gray-200 flex-1">{{ line }}</p>
      <UIcon name="i-lucide-user" class="text-blue-400" />
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{ transcript: string }>()
const lines = computed(() => props.transcript.split(/\r?\n/).filter(l => l))
</script>

// src/components/notes/transcript-display.tsx
'use client'

import { Mic, User } from 'lucide-react'

interface TranscriptDisplayProps {
  transcript: string
}

export function TranscriptDisplay({ transcript }: TranscriptDisplayProps) {
  const lines = transcript.split(/\r?\n/).filter(line => line.trim())

  return (
    <div className="space-y-1 p-4 bg-muted rounded-lg h-64 overflow-auto">
      {lines.map((line, i) => (
        <div key={i} className="flex items-start gap-2">
          <Mic className="text-green-500 w-4 h-4 mt-0.5 shrink-0" />
          <p className="text-sm flex-1">{line}</p>
          <User className="text-blue-500 w-4 h-4 mt-0.5 shrink-0" />
        </div>
      ))}
      {lines.length === 0 && (
        <div className="flex items-center justify-center h-full text-muted-foreground">
          <p>Transcript will appear here...</p>
        </div>
      )}
    </div>
  )
}
